name: calcprint
description: A tool for calculating the printing cost of 3D print items.
publish_to: none
version: 0.1.0+1

repository: https://github.com/JHubi1/calcprint
homepage: https://calcprint.com

environment:
  sdk: ^3.7.0
  flutter: 3.29.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any # dependency hell
  material_symbols_icons: ^4.2815.1
  universal_web: ^1.1.1
  auto_route: ^10.1.0+1
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  pretty_qr_code: ^3.4.0
  shared_preferences: ^2.5.3
  get_time_ago: ^2.3.2
  widgets_to_image: ^2.0.1
  country_flags: ^3.3.0
  strgad: ^0.1.0+1
  pwa_install:
    git:
      url: https://github.com/daniele-sforza/pwa_install

  # because `dynamic_color` doesn't fully support Material You surface colors:
  # > https://github.com/material-foundation/flutter-packages/issues/574
  dynamic_system_colors: ^1.8.0 # dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.1.0
  gitbaker: ^0.0.6

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: NotoSansMono
      fonts:
        - asset: assets/fonts/NotoSansMono-VariableFont_wdth,wght.ttf
  assets:
    - NOTICE
    - assets/data/
