name: Building
on:
  # push:
  #   branches: [main]
  #   paths:
  #     - lib/**
  #     - pubspec.yaml
  #     - assets/data/**
  #     - web/**
  #     - LICENSE
  #     - NOTICE
  #     - makefile
  #     - .github/workflows/build.yml
  workflow_dispatch:
  release:
    types:
      - published
      - unpublished
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get resolved ref
        id: latest
        run: |
          set -ex
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "ref=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')" >> $GITHUB_OUTPUT
          else
            echo "ref=main" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.latest.outputs.ref }}
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      - name: Building
        run: |
          flutter config --disable-analytics --no-cli-animations
          make buildWeb
          cp build/web/index.html build/web/404.html
      - id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
